### ISSUE TITLE
Maven can't obtain pi4j-core

### ISSUE THREAD

**Issue by SmirnoffYM** [Pi4J/pi4j-v1#113]
Hello. I'm trying to add pi4j-core:1.0-SNAPSHOT dependency to my project via Maven, but unfortunately I'm receiving this build error:

`Unable to get dependency information: Unable to read the metadata file for artifact 'com.pi4j:pi4j-core:jar': Invalid JDK version in profile 'doclint-java8-disable': Unbounded range: [1.8, for project com.pi4j:pi4j-parent`
  `com.pi4j:pi4j-core:jar:1.0-SNAPSHOT`

`from the specified remote repositories:`
  `central (http://repo1.maven.org/maven2),`
  `oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)`

I'm using JDK 1.8.0_20 and Maven 2.2.1. Maybe replacing [1.8, with [1.8,) in pi4j-parent-1.0-SNAPSHOT.pom will solve the problem?

**Comment by aharonha** [comment]
The root cause is an invalid profile activator on a dependency to google gson.
It was fixed and deployed on Nov 20th.
https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/
please add to pom.xml

`````` xml
<dependencyManagement>
<dependencies>
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.3.1</version>```
....
``````

**Comment by SmirnoffYM** [comment]
Hello. It doesn't help: I'm still receiving the same error. BTW, pi4j doesn't depend on gson (as I know) and my project too.

**Comment by aharonha** [comment]
The problem is that there is a dependency that does. Google search showed me this one, but there might be others. I'll check for more profiles configurations later on today.
